# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - arm
      - arm64
    goarm:
      - '7'
    goos:
      - linux
      - darwin

dockers:
  - image_templates:
    - ghcr.io/ninjaprox/quote-share:{{ .Tag }}-arm64
    use: buildx
    build_flag_templates:
    - --pull
    - --platform=linux/arm64
    goarch: arm64
    extra_files:
      - fonts/Arsenal/Arsenal-Bold.ttf
      - fonts/Arsenal/Arsenal-BoldItalic.ttf
      - fonts/Arsenal/Arsenal-Italic.ttf
      - fonts/Arsenal/Arsenal-Regular.ttf
      - fonts/Arsenal/OFL.txt
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Black.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-BlackItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Bold.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-BoldItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraBold.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraBoldItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraLight.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraLightItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Italic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Light.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-LightItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Medium.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-MediumItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Regular.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-SemiBold.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-SemiBoldItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Thin.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ThinItalic.ttf
  - image_templates:
    - ghcr.io/ninjaprox/quote-share:{{ .Tag }}-armv7
    use: buildx
    build_flag_templates:
    - --pull
    - --platform=linux/arm/v7
    goarch: arm
    goarm: 7
    extra_files:
      - fonts/Arsenal/Arsenal-Bold.ttf
      - fonts/Arsenal/Arsenal-BoldItalic.ttf
      - fonts/Arsenal/Arsenal-Italic.ttf
      - fonts/Arsenal/Arsenal-Regular.ttf
      - fonts/Arsenal/OFL.txt
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Black.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-BlackItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Bold.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-BoldItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraBold.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraBoldItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraLight.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraLightItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Italic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Light.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-LightItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Medium.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-MediumItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Regular.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-SemiBold.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-SemiBoldItalic.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-Thin.ttf
      - fonts/Be_Vietnam_Pro/BeVietnamPro-ThinItalic.ttf

docker_manifests:
- name_template: ghcr.io/ninjaprox/quote-share:{{ .Tag }}
  image_templates:
  - ghcr.io/ninjaprox/quote-share:{{ .Tag }}-arm64
  - ghcr.io/ninjaprox/quote-share:{{ .Tag }}-armv7

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
